name: Build md cache and json files

on:
  push:
    branches:
      - netlfiy-test
      - astro
  workflow_dispatch:

jobs:
  build-pipeline-json:
    runs-on: ubuntu-latest

    steps:
      # Set up the main website repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Don't do a shallow clone

      # install npm dependencies
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install

      - name: create pipeline.json
        run: npm run build-pipeline-json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Commit and push the changes
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_action
